# Railway Configuration File
# Save as railway.toml in the backend directory

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 5

[environments]
  [environments.production]
    PORT = "8000"
    ENVIRONMENT = "production"
    CORS_ORIGINS = "https://your-production-domain.com"
    API_HOURLY_RATE = "75"